- .github/CODEOWNERS
- tailwind.config.ts
> tailwind.config.ts에 fontSize 추가와 누락되었던 CODEOWNERS 파일을 추가했습니다
> 🔀 tailwind.config.ts에 fontSize 추가

- src/app/_provider/TanstackProvider.tsx
저번에 추가하지 못한 use client를 추가하였습니다
#{ISSUE_ID}
> 🔀 provider에 use client 추가

- tailwind.config.ts
fontSize 변경
기존 h1-h4, body1-body6, caption1-caption6 에서
title1M, body1B, caption1B 처럼 피그마에 더 직관적인 이름으로 변경
> 🔀 fontSize title 변경

- package-lock.json
- package.json
며칠 전 발견된 [middleware 우회 취약점](https://www.linkedin.com/posts/blackcon_nextjs-cve-websecurity-activity-7309608543437893632-xau8?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAEPNHu8BcTYv7EThCTTAfiY0PI5XhJ0sWZo)이 해결된 최신버전의 next로 업그레이드 했습니다
> 🔀next 버전 업그레이드

- .github/workflows/nodeJs-ci.yml
팀원의 pr이 열린 후 코드 리뷰까지 이루어지는 기간이 길어져 pr 생성시 ci와 동시에 mention이 진행되도록 만들었습니다.
> 🔀 pr 생성 시 디스코드 맨션 기능 추가

- src/entities/club/ui/imageUploader/index.tsx
기존 image input에 갯수 및 이미지 형식 제한이 존재하지 않아 여러 장의 이미지가 초과 등록되던 점을 제한시켰습니다.
> 🔀 image input 갯수 및 형식 제한

- next.config.mjs
- src/app/api/neis/meal/route.ts
- src/app/api/neis/schedule/route.ts
- src/entities/home/api/getMeal.ts
- src/entities/home/api/getSchedule.ts
- src/entities/home/model/useMeal.ts
- src/entities/home/model/useSchedule.ts
- src/entities/home/ui/MealBoard/index.tsx
- src/entities/home/ui/ScheduleBoard/index.tsx
- src/shared/types/meal.ts
시간표 요청 시 필요한 param을 추가하였고 급식표를 요청하는 로직과 api를 수정하였습니다.
> 🔀 급식판, 시간표 수정

- src/app/api/admin/massage/route.ts
- src/app/api/admin/self-study/route.ts
- src/app/api/attend/club/route.ts
- src/app/api/auth/find-password/route.ts
- src/app/api/auth/reset-password/route.ts
- src/app/api/auth/sign-in/route.ts
- src/app/api/auth/sign-up/route.ts
- src/app/api/classroom/route.ts
- src/app/api/club/clublist/route.ts
- src/app/api/club/create-club/route.ts
- src/app/api/club/edit-club/route.ts
- src/app/api/club/leave/route.ts
- src/app/api/image/route.ts
- src/app/api/massage/route.ts
- src/app/api/massage/status/route.ts
- src/app/api/music/like/route.ts
- src/app/api/music/route.ts
- src/app/api/neis/meal/route.ts
- src/app/api/neis/schedule/route.ts
- src/app/api/self-study/route.ts
- src/app/api/self-study/status/route.ts
axiosError 정의 시 message 정의 되어 실제 response인 reason의 message가 출력되지 않던 점을 reason으로 변경하여 출력되도록 수정했습니다.
> 🔀 에러 메시지 이름 변경

- src/app/api/auth/student/sign-up/route.ts
- src/app/api/auth/teacher/sign-up/route.ts
- src/entities/signup/api/postSignup.ts
- src/entities/signup/model/formType.ts
- src/entities/signup/model/useSignup.ts
- src/entities/signup/ui/SignupForm/index.tsx
- src/shared/hooks/useUser.ts
> 🔀 회원가입 학생/선생님 구분

- src/shared/types/dormitory.ts
- src/widgets/dormitory/model/useDeleteMassage.ts
- src/widgets/dormitory/model/useDeleteSelfStudy.ts
- src/widgets/dormitory/model/useDispatchMassage.ts
- src/widgets/dormitory/ui/massage/footer/index.tsx
- src/widgets/dormitory/ui/reservationList/index.tsx
- src/widgets/dormitory/ui/selfStudyBoard/footer/index.tsx
post,delete 이벤트 이후 다시 massage와 selfstudy의 데이터를 받아오도록 추가했습니다.
> 🔀기숙사 신청 데이터 재요청 추가

- src/shared/ui/FilterContainer/index.tsx
- src/shared/ui/Header/index.tsx
header의 관리자 옵션이 일반 유저에게 보이는 오류 발견 후 ROLE 확인 기능을 포함했습니다
> 🔀 헤더 관리자 확인 기능 추가

- src/entities/home/model/useMeal.ts
- src/entities/home/ui/MealBoard/index.tsx
- src/entities/home/ui/ProfileContainer/index.tsx
- src/entities/home/ui/ScheduleBoard/index.tsx
- src/views/home/ui/home/index.tsx
- src/widgets/home/ui/DormitoryPanel/index.tsx
- src/widgets/home/ui/OverviewPanel/index.tsx
> 🔀 메인 페이지 반응형 수정

- src/entities/home/ui/MealBoard/index.tsx
로컬에서는 원인이 안 보이는 급식판 버튼 표시 에러를 수정하고 있습니다.ㄹ
#{ISSUE_ID}
> 🔀  급식판 표시 에러

- src/entities/home/ui/MealBoard/index.tsx
> 🔀 급식표 초기값 변경

- src/widgets/home/model/useFetchMassage.ts
- src/widgets/home/model/useFetchSelfStudy.ts
- src/widgets/home/store/useMassageStore.ts
- src/widgets/home/store/useSelfStudyStore.ts
- src/widgets/home/ui/DormitoryPanel/index.tsx
> 🔀 신청 취소 기능 추가

- src/widgets/home/ui/DormitoryPanel/index.tsx
> 어떤 문제가 발생한 이유와, 해결한 방법을 작성해주세요.
#{ISSUE_ID}
> ✨ Fix: message

- src/entities/home/ui/ProfileContainer/index.tsx
> 🔀 마이페이지 width 수정

- src/entities/dormitory/ui/MusicItem/index.tsx
width를 절대 사이즈로 만들어 고정했습니다.
#84 
> 🔀 좋아요 클릭 시 움직이는 아이콘 변경

- src/widgets/dormitory/model/useDispatchMusic.ts
- src/widgets/dormitory/ui/music/footer/index.tsx
음악 신청이 다수 진행되던 오류가 있었습니다.
mutate 성공 후 로딩이 해제되도록 추가했습니다
#87 #82 
> 🔀 기상 음악 신청 로딩 추가

- src/shared/ui/Checkbox/index.tsx
> 🔀 개인정보처리방침 아이콘 가시화

- src/entities/dormitory/ui/MusicItem/index.tsx
> 🔀 좋아요 아이콘 크기 조정

- package-lock.json
- package.json
- src/app/_provider/TanstackProvider.tsx
- src/entities/home/model/useMeal.ts
- src/entities/home/ui/MealBoard/index.tsx
- src/entities/home/ui/ScheduleBoard/index.tsx
- tsconfig.json
급식 대쉬보드에 있던 캐싱, 날짜 넓이 이슈를 해결했습니다.
#98 #97
> 🔀 급식 대쉬보드 이슈 수정

- src/entities/dormitory/model/useAdminDeleteMusic.ts
- src/entities/dormitory/model/useDeleteMusic.ts
- src/entities/dormitory/ui/MusicItem/index.tsx
- src/shared/assets/icons/BigArrowRight.tsx
- src/widgets/dormitory/model/useDispatchMusic.ts
- src/widgets/dormitory/store/useMusicTypeStore.ts
- src/widgets/dormitory/ui/music/header/index.tsx
- src/widgets/dormitory/ui/music/index.tsx
- src/widgets/dormitory/ui/music/list/index.tsx
> 🔀 기상음악 레이아웃 변경

- src/entities/signup/ui/PrivacyPolicyModal/index.tsx
- src/entities/signup/ui/SignupCheckbox/index.tsx
- src/entities/signup/ui/SignupForm/index.tsx
- src/shared/assets/icons/CheckBoxTrue.tsx
누락되었던 개인정보 처리방침 모달을 추가했습니다.
#119 
> 🔀 개인정보 처리방침 모달 추가

- src/widgets/dormitory/ui/music/header/index.tsx
최신순을 기본으로 불러오던 것을 좋아요 순을 우선으로 불러오도록 수정했습니다
> 🔀 기상음악 기본 정렬 수정

- src/widgets/dormitory/ui/music/notify/index.tsx
> 🔀 기상음악 공지사항 수정

- .github/CODEOWNERS
- .github/workflows/nodeJs-ci.yml
기존 github workflow가 정상 작동하지 않아 README 참고 후 수정했습니다.
> 🔀 workflow 수정

- src/app/(pages)/manager/page.tsx
- src/entities/dormitory/api/patchAttend.ts
- src/entities/dormitory/model/useAttendReservation.ts
- src/entities/home/model/checkApply.ts
- src/shared/types/dormitory.ts
- src/widgets/dormitory/model/useDispatchMassage.ts
- src/widgets/dormitory/model/useFetchMassageList.ts
- src/widgets/dormitory/model/useFetchSelfStudyList.ts
- src/widgets/dormitory/ui/massage/index.tsx
- src/widgets/dormitory/ui/reservationList/index.tsx
- src/widgets/dormitory/ui/selfStudyBoard/index.tsx
- src/widgets/home/model/useFetchMassage.ts
기존 자습 출석이 제대로 진행이 안 되고 있었습니다.
patch의 params가 제대로 전달이 되지 않아 발생한 문제였습니다.
> 🔀 기숙사 자습 출석 오류 수정

- .github/workflows/nodeJs-ci.yml
- src/entities/signIn/model/useSignin.ts
로그인 시 발생하는 오류를 사용자가 볼 수 있도록 수정했습니다.
> 🔀 로그인 오류 메시지 가시화

- src/entities/signup/model/useSignup.ts
회원가입 에러 발생 시 사용자가 에러 메시지를 볼 수 있도록 수정했습니다.
> 🔀 회원가입 toast 수정

- package-lock.json
npm update로 패키지의 변경 사항을 적용하고 npm dedupe를 이용하여 중복된 npm 패키지를 제거하였습니다.
> 🔀 package.lock 파일 중복 패키지 제거

- src/app/api/auth/sign-in/route.ts
- src/middleware.ts
이전에 제작했던 KST converter에 있던 `toUTCString()`을 `(expired + 09:00)`으로 수정했습니다.
> 🔀 expire 방식 변경

- src/app/layout.tsx
metadata keyword, open graph를 추가하였습니다.
> 🔀 메타데이터 추가작성

- src/widgets/dormitory/ui/reservationList/index.tsx
스크롤바가 위로 조금 더 올라가 있는 걸 확인하여 수정했습니다.
> 🔀자습신청 스크롤바 오류

- src/entities/dormitory/ui/BorderDropdown/index.tsx
> 🔀드롭다운 배경색 변경

- src/entities/home/ui/ApplyBoard/index.tsx
- src/widgets/dormitory/ui/massage/footer/index.tsx
- src/widgets/dormitory/ui/selfStudyBoard/footer/index.tsx
자습 신청 활성화 여부 확인 중 로딩중 텍스트가 뜨도록 설정했습니다.
> 🔀 자습 신청 로딩중 글씨 추가

- src/entities/signup/ui/PrivacyPolicyModal/index.tsx
개인정보 수집 동의 과정에 성별의 수집 내용이 기재되어있지 않아 추가하였습니다
#169 
> 🔀 개인정보 수집 동의서 성별 조항 추가
